In [2]:
import numpy as np
import torch
import cv2

1. OpenCV读取出来的数据排列为HWC
2. Tensorflow使用的数据排列格式是BHWC，通常指Conv2d要求的格式
3. PyTorch使用的数据排列格式是BCHW

In [78]:
class Matrix:
    def __init__(self, data, shape, format="HWC"):
        self.data = data
        self.shape = shape
        self.format = format
        self.mat = np.array(data).reshape(*shape)
        
    def __repr__(self):
        return f"Matrix{{ \nformat = {self.format}  \nshape  = {self.shape} \ndata   = {self.data} \nmat    = \n{self.mat}\n}}"
    
    def transpose(self, format):
        index = [0] * 3
        
        for j in range(len(format)):
            for i in range(len(self.format)):
                if format[j] == self.format[i]:
                    index[j] = i
                    break
        
        new_mat = self.mat.transpose(*index)
        return Matrix(new_mat.reshape(-1), new_mat.shape, format)

In [82]:
m1 = Matrix(np.arange(8), (2, 2, 2), "HWC")
m1.transpose("CHW")

Matrix{ 
format = CHW  
shape  = (2, 2, 2) 
data   = [0 2 4 6 1 3 5 7] 
mat    = 
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]
}

In [83]:
m1 = Matrix(np.arange(8), (2, 2, 2), "HCW")
m1.transpose("CHW")

Matrix{ 
format = CHW  
shape  = (2, 2, 2) 
data   = [0 1 4 5 2 3 6 7] 
mat    = 
[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]
}