# numpy 广播

numpy广播用于不同shape的数组相加，主要是用`numpy.tile(A, reps)`方法去叠片，把低维度的数组横向和纵向叠加成高维度的数组

`reps`用一个数组表示分别横向和纵向要重复多少次

```python
a = np.array([0, 1, 2])
np.tile(a, 2)
array([0, 1, 2, 0, 1, 2])
np.tile(a, (2, 2))
array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])
np.tile(a, (2, 1, 2))
array([[[0, 1, 2, 0, 1, 2]],
       [[0, 1, 2, 0, 1, 2]]])
```

In [18]:
d13  = np.array([1,2,3])
d14  = np.arange(1,5)

d22  = np.array([[1,2],[3,4]])
d23  = np.array([[1,2],[3,4],[5,6]])
d26 = np.zeros([2,6],dtype=np.int)

d41  = np.array([[1],[2],[3],[4]])
d43  = np.zeros([4,3], dtype='int')

d243 = np.zeros([2,4,3], dtype='int')

列向量和行向量可以相加，会互相补全，不需要考虑维度

- d14 + d41 补成两个4x4
- d13 + d41 补成两个4x3

In [19]:
# d41 + d14 补成两个4x4
d41_44 = np.tile(d41, [1,4])
d14_44 = np.tile(d14, [4,1])
print(f'''
d41 >> 44:
{d41_44}
d14 >> 44:
{d14_44}
sum:
{d41_44+d14_44}
d14+d41:
{d41+d14}
''')

print('d13+d41同理')
print(d13 + d41) # 补成两个4x3


d41 >> 44:
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
d14 >> 44:
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
sum:
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
d14+d41:
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]

d13+d41同理
[[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


`n-d + 1-d` 需要保证列相等，而n-d与列向量相加需要保证行相等。

如果是倍数关系，我本以为也会自动tile，结果没有。除非手动tile成相同维度的数组

In [20]:
##########以下都会失败##########
# d26 + np.array([1,2,3,4]) # 4列和6列，不能相加
# d26 + np.array([1,2,3])  # 6列和3列，也不能自动tile
##############################

# 手动扩展当然没问题，shape都一致了
print(d26 + np.tile(d13, [2,2]))

# 或者满足列数一致与行数一致的任何一条，也可以自动扩展
print(d26 + np.arange(6))          # 都是6列 
print(d26 + np.array([[11],[12]])) # 都是2行

[[1 2 3 1 2 3]
 [1 2 3 1 2 3]]
[[0 1 2 3 4 5]
 [0 1 2 3 4 5]]
[[11 11 11 11 11 11]
 [12 12 12 12 12 12]]


> 非行向量、列向量，都不是广播的范围，即如果是m行n列，且$m, n \neq 1$，除非维度相同，否则不能相加

> 单元素数组可以横向扩展和纵向扩展后相加（这个后续专门讲）

**3d + nd**

在写代码测试前，我先断个言：

2x4x3的三维数组，按课程所说的4*3的数组叠两层来理解

1. 与4x1的列向量能直接相加
2. 与1x3的行向量能直接相加
3. 与2x3这样即使列数相等，行数成倍数关系的数组，也不能相加
4. 但与4x3的向量可以相加

下面来一一测试

In [21]:
# 4x1
print(d243 + d41)
print(d243 + d13)
# print(d243 + d23)   #  >>>> 即使能tile(d23, [2,1])，也不会调用
print(d243 + d43)

[[[1 1 1]
  [2 2 2]
  [3 3 3]
  [4 4 4]]

 [[1 1 1]
  [2 2 2]
  [3 3 3]
  [4 4 4]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [25]:
s = [[15]] # 单元素可以随意相加
d243+s

array([[[15, 15, 15],
        [15, 15, 15],
        [15, 15, 15],
        [15, 15, 15]],

       [[15, 15, 15],
        [15, 15, 15],
        [15, 15, 15],
        [15, 15, 15]]])

In [43]:
d244 = np.zeros((2,4,4),np.int)
d241 = np.ones((2,4,1), np.int)
# d244+d22 # 行列成倍数而不是有一方相等的向量不能相加
d244 + d241 # 列向量包成三维向量仍可以相加，行向量同理
d214 = np.ones((2,1,4), np.int)
d244 + d241

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

不管是高维还是低维，只要有一方最里层是(1,1)即单元素为一个二维数组，
- 低维能向高维扩展
- 高维也能把(1,1)的里层扩展成跟低维一致的(m,n)

In [4]:
import numpy as np
a = np.zeros((3,5))
b = np.arange(3)
a[:,1] = b                 # 索引取出最低维就变成(3,)而不是(3,1)了
a[:,4:5] = b[...,None]     # 但是用切片来取就不会降维 [:, 4:5],而不是[:, 4], 虽然数据是同一列
a[:,None,3] = b[...,None]  # 临时给最低维加一个np.newaxis
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 1.],
       [0., 2., 0., 2., 2.]])