### 什么是Pytorch

An open source machine learning framework that accelerates the path from research prototyping to production deployment.

一个加速了从研究原型到生成部署过程的机器学习框架

---

### 相比于Numpy， Pytorch的优点有哪些？
- 支持高效的NVIDIA-GPU计算，是使用CUDA、CUDNN提供的在GPU上高性能计算的支持（例如：矩阵乘法、卷积等）
    - CUDA(Compute Unified Device Architecture)是NVIDIA推出的基于NVIDIA显卡的并行计算架构。（了解）
    - cuDNN（NVIDIA CUDA Deep Neural Network library）是经GPU加速的深度学习网络库，可以大幅度优化标准层(backward、forward、conv2d、pooling等)的实现（了解）
- 支持自动微分（动态神经网络，基于运行时跟踪技术的自动微分框架）
- 有众多的API可以进行调用，方便开发

---

### Pytorch 相关连接

官方地址：https://pytorch.org/

官方教程地址：https://pytorch.org/tutorials/

官方API地址：https://pytorch.org/docs/stable/index.html

官方代码地址：https://github.com/pytorch/pytorch

.whl文件下载地址： https://download.pytorch.org/whl/torch_stable.html



----
### Pytorch的安装

- 对于CPU的安装命令如下：
    - pip install torch==1.5.1 torchvision==0.6.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
    - .whl文件安装：pip install xxxx.whl
- 对于GPU的安装如下：
    - 第一步：安装NVIDIA显卡驱动
    - 第二步：下载安装CUDA  https://developer.nvidia.com/zh-cn/cuda-downloads
    - 第三步：下载并安装cuDNN  https://developer.nvidia.com/rdp/cudnn-archive
    - 第四步：找到对应的torch版本和torchvision的版本 https://github.com/pytorch/vision
    - 第五步：选择对应的torch的whl文件下载安装（根据CUDA版本进行安装）
    - 第六步：选择对应的torchvision的whl文件下载安装（根据CUDA版本进行安装）

注意：不选择最新版本的原因是为了和后期TensorRT和cuda进行版本的匹配    

---

### Pytorch常用库介绍

In [12]:
import torch  # 导入pytorch的核心支持
# import torch.autograd  # 一个自动求导库，支持所有torch张量求导操作
import torch.nn  # 与autograd深度继承的神经网络库，最大限度的提高灵活性
import torch.utils  # 包含数据加载器(DataLoader)和其他实用便利的函数工具

import torchvision  # 导入pytorch的视觉库，里面包含了经典模型的实现，可以直接使用
import torchvision.datasets  # datasets数据集，常用的小数据集基本都在这里
import torchvision.transforms  # transforms 是图像变换用的函数
import torchvision.models # models 常用的经典模型，比如 VGG，resnet，mobilenet等等

---

## Pytorch常用命令

### 查看pytorch的版本

In [1]:
import torch

In [2]:
torch.__version__

'1.5.1'

### 查看torchvision的版本

In [3]:
import torchvision

In [4]:
torchvision.__version__

'0.6.1'

### 查看cuda的版本

In [5]:
torch.version.cuda

### 自定义张量

In [7]:
torch_number = torch.tensor([1, 2, 3])
torch_number

tensor([1, 2, 3])

### 创建空张量，不进行初始化

In [8]:
value = torch.empty(3, 3)
value

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### 创建随机张量

In [9]:
value = torch.rand(3, 3)  # 均匀分布
value

tensor([[0.0865, 0.0093, 0.2168],
        [0.9201, 0.3807, 0.0112],
        [0.3418, 0.9668, 0.2764]])

In [10]:
value = torch.randn(3, 3)  # 标准正态分布
value

tensor([[ 0.4853,  0.7402,  0.6667],
        [-0.7643,  0.0793, -0.9203],
        [-1.7996,  2.1761, -0.5008]])

In [11]:
value = torch.normal(mean=0, std=1, size=(3,3))  # 离散正态分布
value

tensor([[ 1.8902,  0.2312,  0.3321],
        [-0.2032, -0.9542, -1.5615],
        [ 0.7143, -0.5852,  0.8983]])

In [12]:
value = torch.randint(3, 5, (3, 3))  # 随机整数
value

tensor([[4, 4, 4],
        [3, 3, 4],
        [3, 3, 3]])

In [13]:
a = torch.empty(3, 3).random_()  # 离散的均匀分布
b = torch.empty(3, 3).uniform_()  # 连续均匀分布
c = torch.empty(3, 3).normal_()   # 离散正太分布

a, b, c

(tensor([[ 7872935.,  4015026.,  5901854.],
         [ 5843279., 15162102.,  6511769.],
         [ 1027384.,   594386., 16295852.]]),
 tensor([[0.6124, 0.0313, 0.4989],
         [0.3132, 0.1884, 0.5024],
         [0.8147, 0.5051, 0.7005]]),
 tensor([[ 0.5152,  0.8388,  1.2941],
         [ 0.3074,  1.3238, -0.1460],
         [ 0.2088,  0.6926, -0.4185]]))

随机数种子

In [14]:
torch.manual_seed(3)
torch.randn(3,3)

tensor([[ 0.8033,  0.1748,  0.0890],
        [-0.6137,  0.0462, -1.3683],
        [ 0.3375,  1.0111, -1.4352]])

### 显示张量的形状

In [15]:
value.shape, value.size()

(torch.Size([3, 3]), torch.Size([3, 3]))

### 查看元素类型

In [167]:
value.dtype

torch.float32

### 获取元素数量

In [17]:
torch.numel(value)

9

### 通过Numpy创建张量

In [16]:
import numpy as np 
import torch

In [17]:
numpy_number = np.ones((1, 2, 3))
torch_number = torch.tensor(numpy_number)
torch_number

tensor([[[1., 1., 1.],
         [1., 1., 1.]]], dtype=torch.float64)

In [18]:
torch_number = torch.tensor(numpy_number, dtype=torch.int32)
torch_number

tensor([[[1, 1, 1],
         [1, 1, 1]]], dtype=torch.int32)

In [19]:
torch_number = torch.tensor((numpy_number), device=torch.device("cuda"))
torch_number

AssertionError: Torch not compiled with CUDA enabled

In [118]:
torch_number = torch.as_tensor(numpy_number, dtype=torch.int32)
torch_number

tensor([[[1, 1, 1],
         [1, 1, 1]]], dtype=torch.int32)

In [119]:
torch_number = torch.as_tensor(numpy_number, device=torch.device("cuda"))
torch_number

tensor([[[1., 1., 1.],
         [1., 1., 1.]]], device='cuda:0', dtype=torch.float64)

### 设置当前默认GPU的ID

torch.cuda.set_device(2)
torch_number = torch.tensor((numpy_number), device=torch.device("cuda"))
torch_number

### 使用arange获取范围值

In [193]:
torch_value = torch.arange(1, 10)
print(torch_value)

numpy_value = np.arange(1, 10)
torch_value = torch.from_numpy(numpy_value)
print(torch_value)
torch_value[0] = 10
print(torch_value)
print("numpy=",numpy_value)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([10,  2,  3,  4,  5,  6,  7,  8,  9])
numpy= [10  2  3  4  5  6  7  8  9]


### view操作-更改tensor的维度

In [168]:
torch_value = torch.arange(1, 10)
torch_value.shape

torch.Size([9])

In [145]:
new_torch_value1 = torch_value.view(3, 3)
new_torch_value1.shape

torch.Size([3, 3])

In [155]:
new_torch_value2 = torch_value.view(3, -1)
new_torch_value2.stride()

(3, 1)

In [156]:
new_torch_value3 = new_torch_value2.permute(1, 0)
new_torch_value3.stride()

(1, 3)

In [157]:
new_torch_value3.view(1, -1)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [158]:
new_torch_value3.is_contiguous()

False

In [160]:
new_torch_value4 = new_torch_value3.contiguous()
new_torch_value4.is_contiguous()

True

In [165]:
new_torch_value4.stride()

(3, 1)

In [166]:
new_torch_value4.view(1, -1)

tensor([[1, 4, 7, 2, 5, 8, 3, 6, 9]])

### reshape = view() + contiguous().view()

In [401]:
torch_value = torch.arange(1, 10)
print(torch_value.shape)

new_torch_value = torch_value.reshape(3, 3)
print(new_torch_value.shape)

new_torch_value2 = torch_value.reshape(3, -1)
print(new_torch_value.shape)

new_torch_value3 = new_torch_value2.permute(1, 0)
print(new_torch_value3.shape)

new_torch_value4 = new_torch_value3.reshape(1, -1)
print(new_torch_value4.shape)

torch.Size([9])
torch.Size([3, 3])
torch.Size([3, 3])
torch.Size([3, 3])
torch.Size([1, 9])


### 创建全零张量

In [22]:
value = torch.zeros(3, 3)
value

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### 生成指定tensor大小的纯0张量

In [195]:
torch_value = torch.randn(3, 5)
torch_value.shape

torch.Size([3, 5])

In [196]:
new_torch_value = torch.zeros_like(torch_value)
print(new_torch_value)
print(new_torch_value.shape)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([3, 5])


### 创建纯1张量

In [197]:
value = torch.ones(3, 3)
value

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### 生成指定tensor大小的纯1张量

In [198]:
new_torch_value = torch.ones_like(torch_value)
print(new_torch_value)
print(new_torch_value.shape)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
torch.Size([3, 5])


### 填充指定的值tensor

In [403]:
torch.full((3, 3), fill_value=0)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### 张量拼接

In [213]:
a = torch.arange(1, 10).view(1, 3, 3)
b = torch.arange(11, 20).view(1, 3, 3)
print(a)
print(a.shape)
print(b)
print(b.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])
tensor([[[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])
torch.Size([1, 3, 3])


In [214]:
c = torch.cat((a, b), dim=0)
print(c)
print(c.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])
torch.Size([2, 3, 3])


In [215]:
c = torch.cat((a, b), dim=1)
print(c)
print(c.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])
torch.Size([1, 6, 3])


In [216]:
c = torch.cat((a, b), dim=2)
print(c)
print(c.shape)

tensor([[[ 1,  2,  3, 11, 12, 13],
         [ 4,  5,  6, 14, 15, 16],
         [ 7,  8,  9, 17, 18, 19]]])
torch.Size([1, 3, 6])


### 张量拆分

In [221]:
a = torch.arange(6).view(2, 3)
print(a)
print(a.shape)
print("="*20)
b, c = torch.chunk(a, 2)
print(b)
print(b.shape)
print("="*20)
print(c)
print(c.shape)

tensor([[0, 1, 2],
        [3, 4, 5]])
torch.Size([2, 3])
tensor([[0, 1, 2]])
torch.Size([1, 3])
tensor([[3, 4, 5]])
torch.Size([1, 3])


### 张量聚集

In [24]:
torch_value = torch.tensor([
    [1, 2],
    [3, 4]
])

index_value = torch.tensor([
    [0, 1],
    [1, 0],
    [0, 0]
])

torch.gather(torch_value, dim=0, index=index_value)

tensor([[1, 4],
        [3, 2],
        [1, 2]])

In [238]:
torch_value = torch.tensor([
    [1, 2],
    [3, 4]
])

index_value = torch.tensor([
    [0, 0],
    [0, 0],
    [0, 0]
])

torch.gather(torch_value, dim=0, index=index_value)

tensor([[1, 2],
        [1, 2],
        [1, 2]])

### 移除dim为1的维度

In [421]:
torch_value = torch.randn(1,3 )
print(torch_value.shape)

new_torch_value = torch.squeeze(torch_value) 
print(torch.squeeze(torch_value).shape)

new_torch_value2 = torch_value.squeeze()
print(new_torch_value2.shape)

torch.Size([1, 3])
torch.Size([3])
torch.Size([3])


### 添加一个为1的维度

In [418]:
torch_value = torch.randn(3, 3)
print(torch_value.shape)

new_torch_value = torch.unsqueeze(torch_value, dim=0)
print(new_torch_value.shape)

new_torch_value2 = torch_value.unsqueeze(0)
print(new_torch_value2.shape)

torch.Size([3, 3])
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])


### 张量转置

In [422]:
torch_value = torch.randn(1, 2, 3, 4, 5)
torch_value.shape

torch.Size([1, 2, 3, 4, 5])

In [423]:
new_torch_value = torch_value.permute(4, 3, 2, 1, 0)
new_torch_value.shape

torch.Size([5, 4, 3, 2, 1])

In [428]:
torch_value = torch.randn(2, 3)
torch_value.shape

torch.Size([2, 3])

In [429]:
new_torch_value = torch_value.transpose(1, 0)
new_torch_value.shape

torch.Size([3, 2])

### 通过索引获取值

In [308]:
torch_value = torch.arange(1, 10).view(3, 3)
torch_value

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [309]:
#value: 1， 2， 3， 4， 5， 6， 7， 8， 9
#index: 0， 3， 2， 3， 4， 5， 6， 7， 8

In [310]:
index_value = torch.tensor([
    [0, 5, 2],
    [1, 8, 1]
])

In [313]:
new_torch_value = torch.take(torch_value, index_value)
new_torch_value

tensor([[1, 6, 3],
        [2, 9, 2]])

### 条件取值

In [322]:
torch_value1 = torch.arange(1, 10).view(3, 3)
torch_value2 = torch.full((3, 3), 0, dtype=torch.int64)

condition = torch.tensor([
    [True, False, True],
    [True, False, True],
    [True, False, True]
])

new_torch_value = torch.where(condition, torch_value1, torch_value2)  # if True torch_value1 else torch_value2
new_torch_value

tensor([[1, 0, 3],
        [4, 0, 6],
        [7, 0, 9]])

In [431]:
x = torch.randn(3, 3)
y = torch.zeros(3, 3)
condition = x > 0
z = torch.where(condition, x, y)
z

tensor([[0.0000, 0.0000, 0.0000],
        [0.1197, 0.0000, 0.7880],
        [0.6926, 1.2539, 0.0000]])

### 激活函数：Sigmoid

In [25]:
torch_value = torch.zeros(1)  #  0
new_torch_value = torch.sigmoid(torch_value)
print(new_torch_value)
print(torch_value.sigmoid())

tensor([0.5000])
tensor([0.5000])


sigmoid_()

In [435]:
print(torch_value)
torch_value.sigmoid_()  # inplace操作
print(torch_value)

tensor([0.])
tensor([0.5000])


### 获取最大索引值

In [436]:
torch_value = torch.arange(1, 10)
print(torch_value)
argmax_index = torch.argmax(torch_value, dim=0)
print(argmax_index)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor(8)


In [367]:
torch_value = torch.arange(9).view(3, 3)
print(torch_value)
argmax_index = torch.argmax(torch_value, dim=1)
print(argmax_index)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([2, 2, 2])


In [368]:
torch_value = torch.arange(9).view(3, 3)
print(torch_value)
argmax_index = torch.argmax(torch_value, dim=1, keepdim=True)
print(argmax_index)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[2],
        [2],
        [2]])


### 去重

In [374]:
torch_value = torch.tensor([1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 6, 6])
torch.unique(torch_value)

tensor([1, 2, 3, 4, 5, 6])

### 获取前k个最大元素

In [438]:
torch_value = torch.tensor([0, 1, 2, 3, 4, 5, 12, 6, 7, 8, 9])

In [439]:
values, index = torch.topk(torch_value, 3)
values, index, torch_value

(tensor([12,  9,  8]),
 tensor([ 6, 10,  9]),
 tensor([ 0,  1,  2,  3,  4,  5, 12,  6,  7,  8,  9]))

### 拉平操作

In [440]:
torch_value = torch.randn(2, 2, 3)
print(torch_value)
print(torch_value.shape)
print("="*30)
new_torch_value = torch_value.flatten()
print(new_torch_value)
print(new_torch_value.shape)

tensor([[[ 0.0452,  0.2865,  0.7418],
         [ 0.6506, -0.0801,  1.5359]],

        [[-0.3968, -0.4348,  0.2056],
         [ 0.4902, -0.6970, -0.6366]]])
torch.Size([2, 2, 3])
tensor([ 0.0452,  0.2865,  0.7418,  0.6506, -0.0801,  1.5359, -0.3968, -0.4348,
         0.2056,  0.4902, -0.6970, -0.6366])
torch.Size([12])


### 矩阵乘法

In [400]:
matrix_a = torch.tensor([
    [1, 2],
    [3, 4]
])

matrix_b = torch.tensor([
    [5, 6],
    [7, 8]
])

print(torch.matmul(matrix_a, matrix_b))
print(matrix_a @ matrix_b)
print(torch.mm(matrix_a, matrix_b))

tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
