### 堆排序

堆排序是简单选择排序的一个进化版本，想要了解堆排序的实现原理，我们需要了解什么是堆

堆有两个特点：
1. 必须是一棵完全二叉树
2. 堆上的每一个节点都必须满足父节点的值大于子节点的值

什么是完全二叉树？

定义：若设二叉树的深度为k，除第 k 层外，其它各层 (1～k-1) 的结点数都达到最大个数，第k 层所有的结点都连续集中在最左边，这就是完全二叉树

![avatar](./00_img/bin_tree.png)

二叉树的形成规则是：从上到下，从左往右一次生成

父节点的值一定要大于子节点的值

![avatar](./00_img/bin_tree2.png)

如何构建堆？

![avatar](./00_img/bin_tree3.png)


![avatar](./00_img/bin_tree6.png)

In [110]:
def heapify(arr, n, i):  # arr 是数组， n 是 len(arr) , i 表示当前的索引值
    if i >= n:
        return
    # 找到子节点 child1 和 child2
    child1 = 2 * i + 1 
    child2 = 2 * i + 2
    max_temp = i

    if child1 < n and arr[child1] > arr[max_temp]:
        max_temp = child1
        
    if child2 < n and arr[child2] > arr[max_temp]:
        max_temp = child2
    
    if max_temp != i:
        arr[max_temp], arr[i] = arr[i], arr[max_temp]
        heapify(arr, n, index)

arr = [8, 9, 1, 7, 2, 3, 5, 4, 6]
print(arr)
heapify(arr, len(arr), 2)
arr

[8, 9, 1, 7, 2, 3, 5, 4, 6]


[8, 9, 5, 7, 2, 3, 1, 4, 6]

遍历每个索引点，得到堆

In [111]:
def bulid_heapify(arr, n):
    last_index = n - 1
    parent = (last_index - 1) // 2
    while parent >= 0:
        heapify(arr, n, parent)
        parent -= 1

arr = [8, 9, 1, 7, 2, 3, 5, 4, 6]
print(arr)
bulid_heapify(arr, len(arr))
arr

[8, 9, 1, 7, 2, 3, 5, 4, 6]


[9, 8, 5, 7, 2, 3, 1, 4, 6]

进行堆排序

实现思路：
1. 将根节点和最一个叶子节点进行数据交换
2. 最后一个叶子节点剔除
3. 更新当前完全二叉树，重复 1、2 步骤

In [112]:
def heap_sort(arr, n):
    bulid_heapify(arr, n)
    i = n - 1
    while i >= 0:
        arr[i], arr[0] = arr[0], arr[i]
        heapify(arr, i, 0)
        i -= 1

arr = [8, 9, 1, 7, 2, 3, 5, 4, 6]
print(arr)
heap_sort(arr, len(arr))
arr

[8, 9, 1, 7, 2, 3, 5, 4, 6]


[1, 2, 3, 4, 5, 6, 7, 8, 9]

----

### 数组的创建

In [113]:
import numpy as np

创建未初始化的数据（随机值）

In [114]:
np.empty([2, 2])

array([[1.3315865 , 0.71527897],
       [1.54540029, 0.00838385]])

In [115]:
np.empty([2, 2], dtype="int")

array([[4608675751656456191, 4604617879790409635],
       [4609638683352337475, 4575986582218048383]])

创建纯零数组

In [116]:
np.zeros(2)

array([0., 0.])

In [117]:
np.zeros([2, 2])

array([[0., 0.],
       [0., 0.]])

In [118]:
np.zeros([2, 2], dtype="int")

array([[0, 0],
       [0, 0]])

创建纯1数组

In [119]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [120]:
np.ones([2, 2], dtype="int")

array([[1, 1],
       [1, 1]])

从已有的数组中创建数组

In [121]:
a = [1, 2, 3]
b = (1, 2, 3)
c = [[1, 2], [3, 4]]
d = [(1, 2),(3, 4)]
e = ((1, 2), (3, 4))
f = ([1, 2], [3, 4])

In [122]:
array = np.asarray(a)
array

array([1, 2, 3])

In [123]:
array = np.asarray(b)
array

array([1, 2, 3])

In [124]:
array = np.asarray(c)
array

array([[1, 2],
       [3, 4]])

In [125]:
array = np.asarray(d)
array

array([[1, 2],
       [3, 4]])

In [126]:
array = np.asarray(e)
array

array([[1, 2],
       [3, 4]])

In [127]:
array = np.asarray(f)
array

array([[1, 2],
       [3, 4]])

从数据范围创建数组

In [128]:
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [129]:
array = np.arange(10, 20, 2)
array

array([10, 12, 14, 16, 18])

-----

### 切片

In [130]:
lists = [1, 2, 3, 4, 5]

lists[2:6]

[3, 4, 5]

一维切片

In [131]:
array = np.arange(10)
array[2:5]

array([2, 3, 4])

In [132]:
array = np.arange(10)
array[2:5:2]

array([2, 4])

多维切片

二维

In [133]:
array = np.array([[1,2,3],[3,4,5],[4,5,6]])
array

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [134]:
array[1:2,:]

array([[3, 4, 5]])

In [135]:
array[:,1:2]

array([[2],
       [4],
       [5]])

三维

In [136]:
array = np.array([[[1, 1, 1],[2, 2, 2],[3, 3, 3]],[[4, 4, 4],[5, 5, 5],[6, 6, 6]],[[7, 7, 7],[8, 8, 8],[9, 9, 9]]])
array

array([[[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]],

       [[7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]]])

In [137]:
array[1:2, :, :]

array([[[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]]])

In [138]:
array[:,1:2,:]

array([[[2, 2, 2]],

       [[5, 5, 5]],

       [[8, 8, 8]]])

In [139]:
array[:, :, 1:2]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

-----

### 广播

![avatar](./00_img/gb.png)

In [140]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])

b = np.array([1,2,3])

# bb = np.tile(b, (4, 1))  # 重复 b 的各个维度

a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

广播(Broadcast)是 numpy 对不同形状(shape)的数组进行数值计算的方式， 对数组的算术运算通常在相应的元素上进行。

![avatar](./00_img/gb2.png)

In [141]:
arr1 = np.array([[0, 0, 0],[1, 1, 1],[2, 2, 2], [3, 3, 3]])  #arr1.shape = (4,3)
arr2 = np.array([1, 2, 3])    #arr2.shape = (3,)
arr_sum = arr1 + arr2
print(arr_sum)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


![avatar](./00_img/gb3.png)

In [142]:
arr1 = np.array([[0, 0, 0],[1, 1, 1],[2, 2, 2], [3, 3, 3]])  #arr1.shape = (4,3)
arr2 = np.array([[1],[2],[3],[4]])    #arr2.shape = (4, 1)

arr_sum = arr1 + arr2
print(arr_sum)

[[1 1 1]
 [3 3 3]
 [5 5 5]
 [7 7 7]]


![avatar](./00_img/gb4.png)

In [143]:
arr1 = np.array([[[0, 1],[2,3],[4,5],[6,7]],[[0, 1],[2,3],[4,5],[6,7]],[[0, 1],[2,3],[4,5],[6,7]]])  #arr1.shape = (4,3)
arr2 = np.array([[0, 1], [2, 3], [4, 5], [6, 7]])    #arr2.shape = (4, 1)

arr_sum = arr1 + arr2
print(arr_sum)

[[[ 0  2]
  [ 4  6]
  [ 8 10]
  [12 14]]

 [[ 0  2]
  [ 4  6]
  [ 8 10]
  [12 14]]

 [[ 0  2]
  [ 4  6]
  [ 8 10]
  [12 14]]]


广播的原则：

- 让所有输入数组都向其中形状最长的数组看齐，形状中不足的部分都通过在前面加 1 补齐。
- 输出数组的形状是输入数组形状的各个维度上的最大值。
- 如果输入数组的某个维度和输出数组的对应维度的长度相同或者其长度为 1 时，这个数组能够用来计算，否则出错。
- 当输入数组的某个维度的长度为 1 时，沿着此维度运算时都用此维度上的第一组值。

需要满足：

- 数组拥有相同形状。
- 当前维度的值相等。
- 当前维度的值有一个是 1。

----

### 随机数

生成0-1之间均匀分布随机数

In [144]:
import numpy as np
np.random.rand(2, 2)

array([[0.05047767, 0.33781589],
       [0.10806377, 0.17890281]])

生成在$[low, high)$上离散均匀分布的整数值，若$high = None$ 则区间为 $[0, low)$

In [145]:
np.random.randint(5, size=(2, 2))

array([[0, 3],
       [1, 4]])

In [146]:
np.random.randint(2, 5, size=(2, 2))

array([[2, 2],
       [4, 4]])

生成服从$N(0, 1)$的标准正态分布

In [147]:
np.random.randn(2, 2)

array([[ 0.57421807,  0.93262232],
       [ 0.09091502, -1.47399517]])

随机数种子

In [148]:
np.random.randn(2, 2)

array([[0.11055806, 0.25367995],
       [0.26488179, 0.72477218]])

In [149]:
np.random.randn(2,2)

array([[-0.53535488, -0.19060493],
       [-0.47067661, -0.36261508]])

In [150]:
np.random.seed(10)
np.random.randn(2, 2)

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385]])

In [151]:
np.random.seed(10)
np.random.randn(2, 2)

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385]])