In [3]:
import numpy as np

In [7]:
A = np.matrix('1,2,3;4,5,6;7,8,9')
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
np.sum(A), np.sum(A, axis=0), np.sum(A, axis=1), np.sum(A, axis=-1)

(45,
 matrix([[12, 15, 18]]),
 matrix([[ 6],
         [15],
         [24]]),
 matrix([[ 6],
         [15],
         [24]]))

In [9]:
B = A.copy()
for i in range(3):
    B[i] = np.vstack(B[i])

C = [[1,2,3],[4,5,6],[7,8,9]]
C[0].append([2,3,4])
C

[[1, 2, 3, [2, 3, 4]], [4, 5, 6], [7, 8, 9]]

In [10]:
c = [[] for _ in range(3)]
c[0].append([1,2,3])
c[0].append([4,5,6])
c[1].append([11,12,13])
c[1].append([14,15,16])
c[2].append([311,312,313])
c[2].append([314,315,316])

In [11]:
for index in range(len(c)):
    c[index] = np.vstack(c[index])
c

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[311, 312, 313],
        [314, 315, 316]])]

In [12]:
np.argmax(A, axis=1)

matrix([[2],
        [2],
        [2]], dtype=int64)

In [13]:
B

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
(A==B).sum()


9

In [15]:
np.random.binomial(10, .7, (3,5))
# np.random.binomial?

array([[8, 6, 6, 6, 7],
       [6, 9, 7, 7, 7],
       [6, 9, 6, 7, 6]])

In [16]:
D = [[[1,2],[3,4],[5,6]],
     [[11,12],[13,14],[15,16]],
     [[21,22],[23,24],[25,26]],
     [[31,32],[33,34],[35,36]],
     [[41,42],[43,44],[45,46]]
    ]
s = np.split(D,[1,2],1)
print(list(zip(*D)))
print(s)
print(len(s))

[([1, 2], [11, 12], [21, 22], [31, 32], [41, 42]), ([3, 4], [13, 14], [23, 24], [33, 34], [43, 44]), ([5, 6], [15, 16], [25, 26], [35, 36], [45, 46])]
[array([[[ 1,  2]],

       [[11, 12]],

       [[21, 22]],

       [[31, 32]],

       [[41, 42]]]), array([[[ 3,  4]],

       [[13, 14]],

       [[23, 24]],

       [[33, 34]],

       [[43, 44]]]), array([[[ 5,  6]],

       [[15, 16]],

       [[25, 26]],

       [[35, 36]],

       [[45, 46]]])]
3


In [17]:
E = [(1,2,3),(4,5,6),(7,8,9)]
F = [[1,2,3],[4,5,6],[7,8,9]]
print(list(zip(*E)))
print(list(zip(*F)))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]
[(1, 4, 7), (2, 5, 8), (3, 6, 9)]


In [18]:
range(1,len(E)-1)

range(1, 2)

In [31]:
np.array(E).T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [26]:
for i in range(3):
    E[i] = np.vstack(E)

array([[ 7.32553873e-01, -6.82907846e-01,  1.97427793e-01],
       [ 2.69734511e-04, -1.41335816e+00, -1.66501790e-01],
       [ 1.40000335e-01,  4.15780877e-01, -6.49215147e-01]])

In [42]:
list(zip(*[[2,3,4], [1,2,3], [7,8,9]]))

[(2, 1, 7), (3, 2, 8), (4, 3, 9)]

In [ ]:
np.append